DROP TABLE ERS_REIMBURSEMENT CASCADE CONSTRAINTS;
DROP TABLE ERS_USERS CASCADE CONSTRAINTS;
DROP TABLE ERS_REIMBURSEMENT_STATUS CASCADE CONSTRAINTS;
DROP TABLE ERS_REIMBURSEMENT_TYPE CASCADE CONSTRAINTS;
DROP TABLE ERS_USER_ROLES CASCADE CONSTRAINTS;

CREATE TABLE ERS_USER_ROLES (
    ERS_USER_ROLE       NUMBER              GENERATED ALWAYS AS IDENTITY,
    USER_ROLE           VARCHAR2(10)        NOT NULL,
    PRIMARY KEY(ERS_USER_ROLE)
);

CREATE TABLE ERS_REIMBURSEMENT_TYPE (
    REIMB_TYPE_ID       NUMBER              GENERATED ALWAYS AS IDENTITY,
    REIMB_TYPE          VARCHAR2(10)         NOT NULL,
    PRIMARY KEY(REIMB_TYPE_ID)
);

CREATE TABLE ERS_REIMBURSEMENT_STATUS(
    REIMB_STATUS_ID     NUMBER              GENERATED ALWAYS AS IDENTITY,
    REIMB_STATUS        VARCHAR2(10)        NOT NULL,
    PRIMARY KEY(REIMB_STATUS_ID)
);

CREATE TABLE ERS_USERS(
    ERS_USERS_ID        NUMBER              GENERATED ALWAYS AS IDENTITY,
    ERS_USERNAME        VARCHAR2(50)        NOT NULL UNIQUE,
    ERS_PASSWORD        VARCHAR2(50)        NOT NULL,
    USER_FIRST_NAME     VARCHAR2(100)       NOT NULL,
    USER_LAST_NAME      VARCHAR2(100)       NOT NULL,
    USER_EMAIL          VARCHAR2(100)       NOT NULL UNIQUE,
    USER_ROLE_ID        NUMBER              NOT NULL,
    PRIMARY KEY(ERS_USERS_ID),
    FOREIGN KEY(USER_ROLE_ID) REFERENCES ERS_USER_ROLES(ERS_USER_ROLE)
);

CREATE TABLE ERS_REIMBURSEMENT (
    REIMB_ID            NUMBER              GENERATED ALWAYS AS IDENTITY,
    REIMB_AMOUNT        NUMBER              NOT NULL,
    REIMB_SUBMITTED     TIMESTAMP           NOT NULL,
    REIMB_RESOLVED      TIMESTAMP,
    REIMB_DESCRIPTION   VARCHAR2(250),
    REIMB_RECEIPT       BLOB,
    REIMB_AUTHOR        NUMBER              NOT NULL,
    REIMB_RESOLVER      NUMBER,
    REIMB_STATUS_ID     NUMBER              NOT NULL,
    REIMB_TYPE_ID       NUMBER              NOT NULL,
    PRIMARY KEY(REIMB_ID),
    FOREIGN KEY(REIMB_AUTHOR) REFERENCES ERS_USERS(ERS_USERS_ID),
    FOREIGN KEY(REIMB_RESOLVER) REFERENCES ERS_USERS(ERS_USERS_ID),
    FOREIGN KEY(REIMB_STATUS_ID) REFERENCES ERS_REIMBURSEMENT_STATUS(REIMB_STATUS_ID),
    FOREIGN KEY(REIMB_TYPE_ID) REFERENCES ERS_REIMBURSEMENT_TYPE(REIMB_TYPE_ID)
);

INSERT INTO ERS_REIMBURSEMENT_STATUS(REIMB_STATUS) VALUES('Pending');
INSERT INTO ERS_REIMBURSEMENT_STATUS(REIMB_STATUS) VALUES('Approved');
INSERT INTO ERS_REIMBURSEMENT_STATUS(REIMB_STATUS) VALUES('Denied');

INSERT INTO ERS_REIMBURSEMENT_TYPE(REIMB_TYPE) VALUES('Lodging');
INSERT INTO ERS_REIMBURSEMENT_TYPE(REIMB_TYPE) VALUES('Travel');
INSERT INTO ERS_REIMBURSEMENT_TYPE(REIMB_TYPE) VALUES('Food');
INSERT INTO ERS_REIMBURSEMENT_TYPE(REIMB_TYPE) VALUES('Other');

INSERT INTO ERS_USER_ROLES(USER_ROLE) VALUES('Employee');
INSERT INTO ERS_USER_ROLES(USER_ROLE) VALUES('Manager');
